// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

import (
	"time"
)

type AccountInput struct {
	Name string `json:"name"`
}

type Mutation struct {
}

type Order struct {
	ID         string     `json:"id"`
	Products   []*Product `json:"products"`
	CreatedAt  time.Time  `json:"createdAt"`
	TotalPrice float64    `json:"totalPrice"`
}

type OrderInput struct {
	AccountID string                 `json:"accountId"`
	Products  []*OrderedProductInput `json:"products"`
}

type OrderedProduct struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Price       float64 `json:"price"`
	Quantity    int     `json:"quantity"`
	Description string  `json:"description"`
}

type OrderedProductInput struct {
	ID       string `json:"id"`
	Quantity int    `json:"quantity"`
}

type PaginationInput struct {
	Skip  *int `json:"skip,omitempty"`
	Limit *int `json:"limit,omitempty"`
}

type Product struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Price       float64 `json:"price"`
	Description string  `json:"description"`
}

type ProductInput struct {
	Name        string  `json:"name"`
	Price       float64 `json:"price"`
	Description string  `json:"description"`
}

type Query struct {
}
